[workspace]

[package]
name = "maxlen"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Length-bounded string and slice/vector"
repository = "https://github.com/PonasKovas/maxlen"
readme = "README.md"

[dependencies]
thiserror = "1.0"
maxlen-macro = "0.1"
